# NUMPY

# 파이썬 리스트와 넘파이 배열 속도 비교

In [3]:
import numpy as np

In [2]:
python_list = [i for i in range(1000000)]

In [4]:
arr = np.array(python_list)

In [5]:
%%timeit
sum(python_list)

6.77 ms ± 63.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%%timeit
np.sum(arr)

332 µs ± 21 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## 넘파이 배열 생성과 기본 속성

In [7]:
arr1 = np.array([1, 2, 3])
type(arr1)

numpy.ndarray

In [9]:
print(arr1)
print([1, 2, 3])
arr1

[1 2 3]
[1, 2, 3]


array([1, 2, 3])

In [8]:
arr1.shape

(3,)

In [12]:
a = (2,)
type(a)

tuple

In [13]:
l = [1, 2, 3]
l[0] = 3
l

[3, 2, 3]

In [14]:
t = (1, 2, 3)
t[0] = 3

TypeError: 'tuple' object does not support item assignment

In [15]:
np.array([1, 2, 3])

array([1, 2, 3])

In [16]:
np.array((1, 2, 3))

array([1, 2, 3])

In [17]:
arr2 = np.array([[1, 2], [3, 4], [5, 6]])
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
arr3 = np.array([[[1, 2], [3, 4]],
                 [[6, 5], [7, 8]],
                 [[4, 6], [5, 5]]])
arr3.shape

(3, 2, 2)

In [20]:
arr2.dtype

dtype('int64')

In [21]:
arr3 = np.array([[[1.0, 2], [3, 4]],
                 [[6, 5], [7, 8]],
                 [[4, 6], [5, 5]]])
arr3.dtype

dtype('float64')

In [22]:
arr3 = np.array([[[1.0, '2'], [3, 4]],
                 [[6, 5], [7, 8]],
                 [[4, 6], [5, 5]]])
arr3.dtype

dtype('<U32')

In [23]:
arr3.ndim

3

In [24]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 인덱싱(indexing)과 슬라이싱(slicing)

In [30]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [31]:
arr[0]

1

In [32]:
arr[-1]

5

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr[0]

array([1, 2, 3])

In [38]:
arr[0][0]

1

In [36]:
arr[0, 0]

1

In [40]:
arr[0, ]

array([1, 2, 3])

- 불리언 인덱싱(Boolean indexing)

In [41]:
arr = np.array([1, 2, 3, 4, 5])
arr[1:3]

array([2, 3])

In [43]:
arr = np.array([1, 2, 3, 4, 5])
b = [False, True, False, True, False]
arr[b]

array([2, 4])

In [44]:
arr > 3

array([False, False, False,  True,  True])

In [45]:
arr[arr > 3]

array([4, 5])

In [46]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 > 3

array([[False, False, False],
       [ True,  True,  True]])

In [47]:
arr2[arr2 > 2]

array([3, 4, 5, 6])

In [49]:
arr = np.arange(10)
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [50]:
arr[3:-1]

array([3, 4, 5, 6, 7, 8])

In [51]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr[-4:]

array([6, 7, 8, 9])

## 배열 연산

In [53]:
a = [1, 2, 3]
b = [4, 5, 6]

In [54]:
a + b

[1, 2, 3, 4, 5, 6]

In [55]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [56]:
a + b

array([5, 7, 9])

In [58]:
# 브로드캐스팅
# [1, 2, 3] + [1, 1, 1]
a + 1

array([2, 3, 4])

In [61]:
arr = np.array([1, 2, 3, 4])
arr.sum(), arr.mean()

(10, 2.5)

In [62]:
np.sum(arr), np.mean(arr)

(10, 2.5)

In [63]:
arr2 = np.array([[1, 3, 2], [2, 3, 4]])
arr2.sum()

15

In [64]:
arr2.sum(axis=0)

array([3, 6, 6])

In [65]:
arr2.mean()

2.5

In [66]:
arr2.mean(axis=0)

array([1.5, 3. , 3. ])

In [67]:
arr2 = np.array([[1, 3, 2], [2, 3, 4]])
arr2.shape

(2, 3)

In [68]:
arr2.reshape(3, 2)

array([[1, 3],
       [2, 2],
       [3, 4]])

In [69]:
arr2.reshape(3, 2, 1)

array([[[1],
        [3]],

       [[2],
        [2]],

       [[3],
        [4]]])