In [6]:
import torch

In [5]:
print(torch.tensor([[1,2], [3, 4]]))

tensor([[1, 2],
        [3, 4]])


In [4]:
print(torch.tensor([[1,2], [3, 4]], device='cuda:0'))

tensor([[1, 2],
        [3, 4]], device='cuda:0')


In [ ]:
#print(torch.tensor([[1,2], [3, 4]], dtype=float))

In [ ]:
temp = torch.tensor([[1, 2], [3, 4]])
print(temp.numpy())

In [ ]:
#temp = torch.tensor([[1, 2], [3, 4]], device='cuda:0')
#print(temp.to('cpu').numpy())

In [2]:
temp = torchFloatTensor([1, 2, 3, 4, 5, 6, 7])
print(temp[0], temp[1], temp[-1])
print('----------------')
peint(temp[2:5], temp[4:-1])

NameError: name 'torchFloatTensor' is not defined

In [3]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([3, 4, 6])
print(w - v)

tensor([2, 2, 3])


In [9]:
temp = torch.tensor([[1, 2], [3, 4]])
print(temp.shape)
print('----------------')
print(temp.view(4, 1))
print('----------------')
print(temp.view(-1))
print('----------------')
print(temp.view(1, -1))
print('----------------')
print(temp.view(-1, 1))

torch.Size([2, 2])
----------------
tensor([[1],
        [2],
        [3],
        [4]])
----------------
tensor([1, 2, 3, 4])
----------------
tensor([[1, 2, 3, 4]])
----------------
tensor([[1],
        [2],
        [3],
        [4]])


In [10]:
import pandas as pd
import torch

In [11]:
data = pd.read_csv('car_evaluation.csv')

In [13]:
x = torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()
y = torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()

KeyError: 'x'

In [14]:
import torchvision.transforms as transforms

In [15]:
mnist_transforms = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,),(1.0,))
])

In [16]:
from torchvision.datasets import MNIST
import requests

In [17]:
download_root = './MNIST_DATASET'
train_dataset = MNIST(download_root, transform=mnist_transforms, train=True, download=True)
valid_dataset = MNIST(download_root, transform=mnist_transforms, train=False, download=True)
test_dataset = MNIST(download_root, transform=mnist_transforms, train=False, download=True)

Failed to download (trying next):
<urlopen error [Errno 110] Connection timed out>



100%|██████████| 9.91M/9.91M [00:00<00:00, 39.2MB/s]


Extracting ./MNIST_DATASET/MNIST/raw/train-images-idx3-ubyte.gz to ./MNIST_DATASET/MNIST/raw

Failed to download (trying next):
<urlopen error [Errno 110] Connection timed out>



100%|██████████| 28.9k/28.9k [00:00<00:00, 1.17MB/s]


Extracting ./MNIST_DATASET/MNIST/raw/train-labels-idx1-ubyte.gz to ./MNIST_DATASET/MNIST/raw

Failed to download (trying next):
<urlopen error [Errno 110] Connection timed out>



100%|██████████| 1.65M/1.65M [00:00<00:00, 10.2MB/s]


Extracting ./MNIST_DATASET/MNIST/raw/t10k-images-idx3-ubyte.gz to ./MNIST_DATASET/MNIST/raw

Failed to download (trying next):
<urlopen error [Errno 110] Connection timed out>



100%|██████████| 4.54k/4.54k [00:00<00:00, 3.87MB/s]


Extracting ./MNIST_DATASET/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./MNIST_DATASET/MNIST/raw



In [ ]:
import torch
from torch.optim import SGD  # 확률적 경사 하강법(SGD) 최적화 알고리즘
from torch.nn import MSELoss  # 평균 제곱 오차 손실 함수
from torch.optim.lr_scheduler import LambdaLR  # 학습률 스케줄러

# 손실 함수 정의: 평균 제곱 오차(MSE)
criterion = MSELoss()

# 모델의 파라미터 정의 (여기서는 예시로 model.parameters() 사용)
model = torch.nn.Linear(10, 1)  # 입력 크기 10, 출력 크기 1의 선형 모델
optimizer = SGD(model.parameters(), lr=0.01, momentum=0.9)
# SGD 최적화: 학습률 0.01, 모멘텀 0.9를 사용

# 학습률 스케줄러 정의
scheduler = LambdaLR(optimizer, lr_lambda=lambda epoch: 0.95 ** epoch)
# LambdaLR: 매 에포크마다 학습률을 0.95의 거듭제곱만큼 감소

# 학습 루프
for epoch in range(1, 101):  # 총 100 에포크 동안 학습
    # 데이터 로더를 통해 배치 단위로 데이터 가져오기 (여기서는 가상 데이터)
    for x, y in [(torch.randn(32, 10), torch.randn(32, 1))]:  # 배치 크기 32
        optimizer.zero_grad()  # 이전 배치에서 계산된 기울기(gradient) 초기화
        loss = criterion(model(x), y)  # 예측 값과 실제 값의 손실 계산
        loss.backward()  # 기울기 계산
        optimizer.step()  # 파라미터 업데이트

    # 에포크마다 학습률 업데이트
    scheduler.step()
