In [1]:
import numpy as np

# 1) 입력 임베딩 X (3 x 4)
X = np.array([
    [0.2, 0.1, 0.5, 0.3],  # I
    [0.4, 0.3, 0.8, 0.1],  # am
    [0.7, 0.6, 0.1, 0.9]   # Sam
])

# 2) Q, K, V를 모두 X로 가정 (W_Q, W_K, W_V = I)
Q = X
K = X
V = X

# 3) QK^T
dot = Q.dot(K.T)
# 4) 스케일링 (d_k=4 -> sqrt(4)=2)
dk = 4
scaled_dot = dot / np.sqrt(dk)

# 5) 행별 softmax
def softmax(row):
    ex = np.exp(row)
    return ex / np.sum(ex)

A = np.apply_along_axis(softmax, 1, scaled_dot)

# 6) 어텐션 결과: A x V
Z = A.dot(V)

print("QK^T =\n", dot)
print("\nScaled (QK^T) / sqrt(dk) =\n", scaled_dot)
print("\nAttention Weights (A) =\n", A)
print("\nFinal Context Embedding (Z) =\n", Z)


QK^T =
 [[0.39 0.54 0.52]
 [0.54 0.9  0.63]
 [0.52 0.63 1.67]]

Scaled (QK^T) / sqrt(dk) =
 [[0.195 0.27  0.26 ]
 [0.27  0.45  0.315]
 [0.26  0.315 0.835]]

Attention Weights (A) =
 [[0.31796066 0.34272475 0.33931459]
 [0.30833315 0.36914179 0.32252506]
 [0.26084658 0.275595   0.46355842]]

Final Context Embedding (Z) =
 [[0.43820224 0.33820224 0.46709159 0.4350438 ]
 [0.43509089 0.33509089 0.48173251 0.41968668]
 [0.48689821 0.38689821 0.39725513 0.52301605]]
